// Generated by scripts/build-images.ts. Do not edit by hand.
// Every photo is an Adobe Stock image licensed through the owner's account (see the
// record on each slot). The people shown are not clients, founders or team members.

export const IMAGE_MANIFEST = {
  "hero-kitchen-table": {
    "aspect": "4:3",
    "variants": [
      {
        "width": 480,
        "height": 360
      },
      {
        "width": 720,
        "height": 540
      },
      {
        "width": 960,
        "height": 720
      },
      {
        "width": 1280,
        "height": 960
      },
      {
        "width": 1600,
        "height": 1200
      }
    ],
    "license": {
      "source": "Adobe Stock (free collection)",
      "licensedVia": "Adobe Stock license-and-download API, owner's connected Adobe account",
      "licenseState": "just_purchased",
      "licenseId": null,
      "licenseType": null,
      "modelRelease": null,
      "aiGenerated": false,
      "stockId": "136756456",
      "licensedAt": "2026-09-26T20:01:02Z"
    }
  },
  "family-at-table": {
    "aspect": "3:2",
    "variants": [
      {
        "width": 480,
        "height": 320
      },
      {
        "width": 720,
        "height": 480
      },
      {
        "width": 960,
        "height": 640
      },
      {
        "width": 1280,
        "height": 853
      }
    ],
    "license": {
      "source": "Adobe Stock (free collection)",
      "licensedVia": "Adobe Stock license-and-download API, owner's connected Adobe account",
      "licenseState": "just_purchased",
      "licenseId": null,
      "licenseType": null,
      "modelRelease": null,
      "aiGenerated": false,
      "stockId": "615558256",
      "licensedAt": "2026-09-26T20:01:14Z"
    }
  },
  "pediatric-visit": {
    "aspect": "3:2",
    "variants": [
      {
        "width": 480,
        "height": 320
      },
      {
        "width": 720,
        "height": 480
      },
      {
        "width": 960,
        "height": 640
      },
      {
        "width": 1280,
        "height": 853
      }
    ],
    "license": {
      "source": "Adobe Stock (free collection)",
      "licensedVia": "Adobe Stock license-and-download API, owner's connected Adobe account",
      "licenseState": "just_purchased",
      "licenseId": null,
      "licenseType": null,
      "modelRelease": null,
      "aiGenerated": false,
      "stockId": "567092912",
      "licensedAt": "2026-09-26T20:02:08Z"
    }
  },
  "listening": {
    "aspect": "16:9",
    "variants": [
      {
        "width": 640,
        "height": 360
      },
      {
        "width": 960,
        "height": 540
      },
      {
        "width": 1280,
        "height": 720
      },
      {
        "width": 1600,
        "height": 900
      }
    ],
    "license": {
      "source": "Adobe Stock (free collection)",
      "licensedVia": "Adobe Stock license-and-download API, owner's connected Adobe account",
      "licenseState": "just_purchased",
      "licenseId": null,
      "licenseType": null,
      "modelRelease": null,
      "aiGenerated": false,
      "stockId": "415870764",
      "licensedAt": "2026-09-26T20:01:00Z"
    }
  },
  "reviewing-bills": {
    "aspect": "4:5",
    "variants": [
      {
        "width": 480,
        "height": 600
      },
      {
        "width": 720,
        "height": 900
      },
      {
        "width": 960,
        "height": 1200
      }
    ],
    "license": {
      "source": "Adobe Stock (free collection)",
      "licensedVia": "Adobe Stock license-and-download API, owner's connected Adobe account",
      "licenseState": "just_purchased",
      "licenseId": null,
      "licenseType": null,
      "modelRelease": null,
      "aiGenerated": false,
      "stockId": "1215379904",
      "licensedAt": "2026-09-26T20:01:16Z"
    }
  },
  "grandmother-granddaughter": {
    "aspect": "4:3",
    "variants": [
      {
        "width": 480,
        "height": 360
      },
      {
        "width": 720,
        "height": 540
      },
      {
        "width": 960,
        "height": 720
      },
      {
        "width": 1280,
        "height": 960
      }
    ],
    "license": {
      "source": "Adobe Stock (free collection)",
      "licensedVia": "Adobe Stock license-and-download API, owner's connected Adobe account",
      "licenseState": "just_purchased",
      "licenseId": null,
      "licenseType": null,
      "modelRelease": null,
      "aiGenerated": false,
      "stockId": "646469521",
      "licensedAt": "2026-09-26T20:00:59Z"
    }
  },
  "training-workshop": {
    "aspect": "3:2",
    "variants": [
      {
        "width": 480,
        "height": 320
      },
      {
        "width": 720,
        "height": 480
      },
      {
        "width": 960,
        "height": 640
      },
      {
        "width": 1280,
        "height": 853
      }
    ],
    "license": {
      "source": "Adobe Stock (free collection)",
      "licensedVia": "Adobe Stock license-and-download API, owner's connected Adobe account",
      "licenseState": "just_purchased",
      "licenseId": null,
      "licenseType": null,
      "modelRelease": null,
      "aiGenerated": false,
      "stockId": "722083959",
      "licensedAt": "2026-09-26T20:02:09Z"
    }
  }
} as const;

export type ImageSlug = keyof typeof IMAGE_MANIFEST;
