// Generated by scripts/build-images.ts. Do not edit by hand.
// Every photo on the site is a licensed, model-released Adobe Stock image.
// People shown are models, not clients, founders or team members.

export const IMAGE_MANIFEST = {
  "hero-kitchen-table": {
    "aspect": "4:3",
    "variants": [
      {
        "width": 480,
        "height": 360
      },
      {
        "width": 720,
        "height": 540
      },
      {
        "width": 960,
        "height": 720
      },
      {
        "width": 1280,
        "height": 960
      },
      {
        "width": 1600,
        "height": 1200
      }
    ],
    "license": {
      "source": "Adobe Stock",
      "license": "Adobe Stock Standard License (Free collection)",
      "licensedOn": "2026-09-26",
      "modelReleased": true,
      "aiGenerated": false,
      "stockId": "136756456"
    }
  },
  "family-at-table": {
    "aspect": "3:2",
    "variants": [
      {
        "width": 480,
        "height": 320
      },
      {
        "width": 720,
        "height": 480
      },
      {
        "width": 960,
        "height": 640
      },
      {
        "width": 1280,
        "height": 853
      }
    ],
    "license": {
      "source": "Adobe Stock",
      "license": "Adobe Stock Standard License (Free collection)",
      "licensedOn": "2026-09-26",
      "modelReleased": true,
      "aiGenerated": false,
      "stockId": "615558256"
    }
  },
  "pediatric-visit": {
    "aspect": "3:2",
    "variants": [
      {
        "width": 480,
        "height": 320
      },
      {
        "width": 720,
        "height": 480
      },
      {
        "width": 960,
        "height": 640
      },
      {
        "width": 1280,
        "height": 853
      }
    ],
    "license": {
      "source": "Adobe Stock",
      "license": "Adobe Stock Standard License (Free collection)",
      "licensedOn": "2026-09-26",
      "modelReleased": true,
      "aiGenerated": false,
      "stockId": "567092912"
    }
  },
  "listening": {
    "aspect": "16:9",
    "variants": [
      {
        "width": 640,
        "height": 360
      },
      {
        "width": 960,
        "height": 540
      },
      {
        "width": 1280,
        "height": 720
      },
      {
        "width": 1600,
        "height": 900
      }
    ],
    "license": {
      "source": "Adobe Stock",
      "license": "Adobe Stock Standard License (Free collection)",
      "licensedOn": "2026-09-26",
      "modelReleased": true,
      "aiGenerated": false,
      "stockId": "415870764"
    }
  },
  "reviewing-bills": {
    "aspect": "4:5",
    "variants": [
      {
        "width": 480,
        "height": 600
      },
      {
        "width": 720,
        "height": 900
      },
      {
        "width": 960,
        "height": 1200
      }
    ],
    "license": {
      "source": "Adobe Stock",
      "license": "Adobe Stock Standard License (Free collection)",
      "licensedOn": "2026-09-26",
      "modelReleased": true,
      "aiGenerated": false,
      "stockId": "1215379904"
    }
  },
  "grandmother-granddaughter": {
    "aspect": "4:3",
    "variants": [
      {
        "width": 480,
        "height": 360
      },
      {
        "width": 720,
        "height": 540
      },
      {
        "width": 960,
        "height": 720
      },
      {
        "width": 1280,
        "height": 960
      }
    ],
    "license": {
      "source": "Adobe Stock",
      "license": "Adobe Stock Standard License (Free collection)",
      "licensedOn": "2026-09-26",
      "modelReleased": true,
      "aiGenerated": false,
      "stockId": "646469521"
    }
  },
  "training-workshop": {
    "aspect": "3:2",
    "variants": [
      {
        "width": 480,
        "height": 320
      },
      {
        "width": 720,
        "height": 480
      },
      {
        "width": 960,
        "height": 640
      },
      {
        "width": 1280,
        "height": 853
      }
    ],
    "license": {
      "source": "Adobe Stock",
      "license": "Adobe Stock Standard License (Free collection)",
      "licensedOn": "2026-09-26",
      "modelReleased": true,
      "aiGenerated": false,
      "stockId": "722083959"
    }
  }
} as const;

export type ImageSlug = keyof typeof IMAGE_MANIFEST;
