/**
 * Exports the site's photographs as responsive AVIF and WebP.
 *
 *   ASSET_MASTERS_DIR=/path/to/masters npm run images:build
 *
 * Masters are the full-resolution Adobe Stock downloads named
 * AdobeStock_<id>.jpeg. They are NOT committed: this repository is public,
 * and redistributing a licensed master as a standalone file is outside the
 * stock license. Only web-resolution derivatives are committed, the same
 * files the site serves anyway.
 *
 * Writes public/images/<slug>-<width>.{avif,webp} and
 * src/allset/content/images.generated.ts (dimensions + license record).
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import sharp from 'sharp';

interface Slot {
  readonly slug: string;
  readonly stockId: string;
  /** When Adobe's API issued the licensed download for this asset (UTC). */
  readonly licensedAt: string;
  readonly aspect: readonly [number, number];
  readonly widths: readonly number[];
  /** sharp gravity or strategy for the crop. */
  readonly position: string | number;
}

const SLOTS: readonly Slot[] = [
  { slug: 'hero-kitchen-table', stockId: '136756456', licensedAt: '2026-09-26T20:01:02Z', aspect: [4, 3], widths: [480, 720, 960, 1280, 1600], position: sharp.strategy.attention },
  { slug: 'family-at-table', stockId: '615558256', licensedAt: '2026-09-26T20:01:14Z', aspect: [3, 2], widths: [480, 720, 960, 1280], position: 'north' },
  { slug: 'pediatric-visit', stockId: '567092912', licensedAt: '2026-09-26T20:02:08Z', aspect: [3, 2], widths: [480, 720, 960, 1280], position: sharp.strategy.attention },
  { slug: 'listening', stockId: '415870764', licensedAt: '2026-09-26T20:01:00Z', aspect: [16, 9], widths: [640, 960, 1280, 1600], position: sharp.strategy.attention },
  { slug: 'reviewing-bills', stockId: '1215379904', licensedAt: '2026-09-26T20:01:16Z', aspect: [4, 5], widths: [480, 720, 960], position: sharp.strategy.attention },
  { slug: 'grandmother-granddaughter', stockId: '646469521', licensedAt: '2026-09-26T20:00:59Z', aspect: [4, 3], widths: [480, 720, 960, 1280], position: 'centre' },
  { slug: 'training-workshop', stockId: '722083959', licensedAt: '2026-09-26T20:02:09Z', aspect: [3, 2], widths: [480, 720, 960, 1280], position: sharp.strategy.attention },
];

/**
 * What the record shows, and nothing more. Each asset was found with
 * Adobe Stock search filtered to the free collection (every result carried
 * isGenTech: false) and licensed through the owner's connected Adobe account
 * with the license-and-download API, which answered state "just_purchased".
 * The API returned no license ID and no model-release status: confirm both,
 * and the license type, in the account's Adobe Stock license history.
 */
const LICENSE = {
  source: 'Adobe Stock (free collection)',
  licensedVia: 'Adobe Stock license-and-download API, owner\'s connected Adobe account',
  licenseState: 'just_purchased',
  licenseId: null,
  licenseType: null,
  modelRelease: null,
  aiGenerated: false,
} as const;

async function main(): Promise<void> {
  const masters = process.env['ASSET_MASTERS_DIR'];
  if (!masters) throw new Error('Set ASSET_MASTERS_DIR to the folder holding AdobeStock_<id>.jpeg masters.');

  const outDir = join(process.cwd(), 'public/images');
  mkdirSync(outDir, { recursive: true });

  const manifest: Record<string, unknown> = {};

  for (const slot of SLOTS) {
    const source = join(masters, `AdobeStock_${slot.stockId}.jpeg`);
    const [aw, ah] = slot.aspect;
    const variants: { width: number; height: number }[] = [];

    for (const width of slot.widths) {
      const height = Math.round((width * ah) / aw);
      const pipeline = sharp(source)
        .rotate()
        .resize(width, height, { fit: 'cover', position: slot.position })
        // sharp strips EXIF (camera, capture data) by default; output is sRGB.
        .toColorspace('srgb');

      await pipeline
        .clone()
        .avif({ quality: 52, effort: 6, chromaSubsampling: '4:2:0' })
        .toFile(join(outDir, `${slot.slug}-${width}.avif`));
      await pipeline.clone().webp({ quality: 74, effort: 6 }).toFile(join(outDir, `${slot.slug}-${width}.webp`));
      variants.push({ width, height });
    }

    manifest[slot.slug] = {
      aspect: `${aw}:${ah}`,
      variants,
      license: { ...LICENSE, stockId: slot.stockId, licensedAt: slot.licensedAt },
    };
    console.log(`${slot.slug}: ${slot.widths.join(', ')}`);
  }

  const file = `// Generated by scripts/build-images.ts. Do not edit by hand.
// Every photo is an Adobe Stock image licensed through the owner's account (see the
// record on each slot). The people shown are not clients, founders or team members.

export const IMAGE_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;

export type ImageSlug = keyof typeof IMAGE_MANIFEST;
`;
  writeFileSync(join(process.cwd(), 'src/allset/content/images.generated.ts'), file);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
